todo: hello hello2 hello3 nonblocking scatter
hello: hello.c
	mpicc hello.c -o hello
hello2: hello2.c
	mpicc hello2.c -o hello2
hello3: hello3.c
	mpicc hello3.c -o hello3
nonblocking: nonblocking.c
	mpicc nonblocking.c -o nonblocking	
scatter: scatter.c
	mpicc scatter.c -o scatter		
clean:
	rm hello hello2 hello3 nonblocking scatter
